import { useEffect, useState } from 'react';
import Container from './components/layout/Container';
import Section from './components/layout/Section';
import Hero from './components/Hero';
import HorizontalExperience from './components/HorizontalExperience';

const phone = '+351910131072';
const commercialEmail = 'atendimento@premiumcars.pt';
const demoAddress = 'Rua da Mobilidade, 24 · 2400-000 Leiria';
const nav = [['Início', '#inicio'], ['Para motoristas', '#experiencia'], ['Candidatura', '#viagem'], ['Contactos', '#contactos']];
function Arrow() { return <span aria-hidden="true">↗</span>; }
function WhatsAppIcon() { return <svg className="contact-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.3-4.7A8.5 8.5 0 1 1 20.5 11.7Z"/><path d="M8.1 7.4c.2-.4.4-.4.7-.4h.5c.2 0 .4.1.5.4l.8 1.9c.1.3.1.5-.1.7l-.6.8c-.2.2-.1.4 0 .6.6 1 1.5 1.8 2.5 2.4.3.1.5.2.7 0l.9-1.1c.2-.2.4-.3.7-.2l1.8.9c.3.1.4.3.4.5 0 .3-.2 1.4-.9 2-.6.5-1.4.8-2.3.6-1.2-.3-2.8-.8-4.7-2.5-1.6-1.5-2.7-3.3-3-4.6-.3-1 .1-1.6.4-2Z"/></svg>; }
function MailIcon() { return <svg className="contact-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1.5"/><path d="m4 7 8 6 8-6"/></svg>; }
type PathIconName = 'car-check' | 'key' | 'profile' | 'search' | 'document' | 'request' | 'car';
function PathIcon({ name, className = 'driver-path-list-icon' }: { name: PathIconName; className?: string }) {
  return <svg className={className} viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
    {name === 'car-check' && <><path d="m4 15 1.8-5.2A2.7 2.7 0 0 1 8.3 8h5.4a2.7 2.7 0 0 1 2.5 1.8L18 15"/><path d="M3 15h16v4H3zM6 19v2m10-2v2M6.5 15h.01m9.99 0h.01"/><path d="m15.5 5 1.5 1.5L20 3.5"/></>}
    {name === 'key' && <><circle cx="8" cy="12" r="4"/><path d="m11.2 9.2 3.3-3.3 3.6 3.6-1.4 1.4-1.2-1.2-1.4 1.4-1.2-1.2-1.7 1.7"/></>}
    {name === 'profile' && <><circle cx="12" cy="8" r="3"/><path d="M6.5 19c.7-3 2.5-4.5 5.5-4.5s4.8 1.5 5.5 4.5"/></>}
    {name === 'search' && <><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4 4"/></>}
    {name === 'document' && <><path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h4M10 13h5m-5 4h5"/></>}
    {name === 'request' && <><path d="M8 4h8m-7 0v3h6V4m-9 2H4v15h16V6h-2"/><path d="M8 12h8m-8 4h5"/></>}
    {name === 'car' && <><path d="m4 15 1.8-5.2A2.7 2.7 0 0 1 8.3 8h7.4a2.7 2.7 0 0 1 2.5 1.8L20 15"/><path d="M3 15h18v4H3zM6 19v2m12-2v2M6.5 15h.01m10.99 0h.01"/></>}
  </svg>;
}
export default function App() {
  const [menu, setMenu] = useState(false);
  const [legal, setLegal] = useState<'privacidade' | 'cookies' | 'legal' | null>(null);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === 'Escape') setMenu(false); }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape); }, []);
  return <>
    <a className="skip-link" href="#main-content">Saltar para o conteúdo</a>
    <HorizontalExperience header={
    <header className="ride-header"><Container className="header-inner"><a className="brand-logo" href="#inicio" aria-label="Premium Ride — início"><img src="/logo.png" alt="Premium Ride" width="500" height="500" /></a><nav aria-label="Navegação principal" className="desktop-nav">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><button className="menu-toggle" aria-expanded={menu} aria-controls="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? 'Fechar' : 'Menu'} <span aria-hidden="true">{menu ? '−' : '+'}</span></button></Container>{menu && <nav id="mobile-menu" className="mobile-nav" aria-label="Navegação móvel">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenu(false)}>{label}</a>)}</nav>}</header>
    } panels={[
      <>
      <Hero/>

      </>,
      <Section key="experiencia" id="experiencia" variant="spacious"><Container className="experience-layout"><div><p className="eyebrow">PARA MOTORISTAS TVDE</p><h2>A sua atividade.<br/><em>O próximo passo.</em></h2><p className="coverage-note">Candidaturas e aluguer de viaturas para atividade TVDE em Lisboa, sujeitos a disponibilidade e análise.</p></div><div className="experience-copy"><p className="large-copy">Procura uma viatura para trabalhar em TVDE ou pretende apresentar-se como motorista? Comece por nos indicar o seu perfil.</p><ol className="booking-steps" aria-label="Como apresentar uma candidatura"><li><span>01</span><div><strong>Escolha a modalidade</strong><small>Aluguer de viatura ou atividade com viatura própria.</small></div></li><li><span>02</span><div><strong>Apresente o seu perfil</strong><small>Contacto, localização, certificado e disponibilidade.</small></div></li><li><span>03</span><div><strong>Conheça as condições</strong><small>A Premium Ride entra em contacto após análise.</small></div></li></ol><a href="#viagem" className="text-link">Apresentar candidatura <Arrow/></a></div></Container></Section>
,      <Section key="viagem" id="viagem" className="journey-section driver-choice-section" variant="spacious"><Container><div className="driver-choice-heading"><p className="eyebrow">CANDIDATURAS TVDE</p><h2>Como pretende<br/><em>começar?</em></h2><p>Escolha a opção que corresponde à sua situação atual.</p></div><div className="driver-paths"><article className="driver-path-card"><div className="driver-path-media"><img src="/ride-bmw-night.jpg" alt="Viatura preparada para atividade TVDE" loading="lazy" width="960" height="640"/></div><div className="driver-path-content"><span className="driver-path-symbol"><PathIcon name="car-check" className="driver-path-main-icon"/></span><h3>Já tenho viatura</h3><p>Já dispõe de veículo para trabalhar em TVDE? Fale com a equipa para apresentar o seu perfil e conhecer os próximos passos.</p><ul><li><PathIcon name="profile"/>Candidatura de motorista</li><li><PathIcon name="search"/>Análise do perfil</li><li><PathIcon name="document"/>Condições sob consulta</li></ul><a href="#contactos" className="driver-path-link">Falar com a Premium Ride</a></div></article><article className="driver-path-card"><div className="driver-path-media"><img src="/ride-bmw-garage.jpg" alt="Viatura premium disponível para aluguer TVDE" loading="lazy" width="960" height="640"/></div><div className="driver-path-content"><span className="driver-path-symbol"><PathIcon name="key" className="driver-path-main-icon"/></span><h3>Preciso de viatura</h3><p>Procura uma viatura para iniciar ou continuar a sua atividade TVDE? Consulte as opções através do formulário da WeGest.</p><ul><li><PathIcon name="request"/>Pedido de aluguer</li><li><PathIcon name="car"/>Disponibilidade de viaturas</li><li><PathIcon name="document"/>Condições apresentadas pela WeGest</li></ul><a href="https://www.wegest.pt/formulario/6009888a-6b73-4b11-bae4-b7256fca13d2" className="driver-path-link" target="_blank" rel="noreferrer">Consultar viatura na WeGest</a></div></article></div><p className="driver-choice-note">A disponibilidade e as condições de aluguer são confirmadas pela entidade responsável após análise do pedido.</p></Container></Section>
,
      <>
      <Section id="contactos" variant="spacious" className="contact-section"><Container><p className="eyebrow">CANDIDATURAS E INFORMAÇÕES</p><h2 className="contact-heading">Quer trabalhar em TVDE?<br/><em>Fale com a Premium Ride.</em></h2><a className="contact-number" href={`tel:${phone}`}>+351 910 131 072</a><div className="contact-actions"><a className="contact-whatsapp" href={`https://wa.me/${phone.replace(/\D/g, '')}?text=${encodeURIComponent('Olá, Premium Ride. Gostaria de conhecer as opções para motoristas TVDE.')}`} target="_blank" rel="noreferrer">Falar pelo WhatsApp <WhatsAppIcon/></a><a className="contact-whatsapp" href={`mailto:${commercialEmail}`}>{commercialEmail} <MailIcon/></a></div><p className="contact-meta">Atendimento 24/7 <span aria-hidden="true">·</span> {demoAddress}</p><p className="contact-meta">Candidaturas por telefone, WhatsApp e e-mail <span aria-hidden="true">·</span> Chamada para a rede móvel nacional</p><p className="demo-disclaimer">Dados de contacto e morada apresentados para demonstração.</p></Container></Section>
    <footer className="ride-footer"><Container><div className="footer-bottom"><span>© {new Date().getFullYear()} Premium Ride</span><div><button onClick={() => setLegal(legal === 'privacidade' ? null : 'privacidade')} aria-expanded={legal === 'privacidade'}>Privacidade</button><button onClick={() => setLegal(legal === 'cookies' ? null : 'cookies')} aria-expanded={legal === 'cookies'}>Cookies</button><button onClick={() => setLegal(legal === 'legal' ? null : 'legal')} aria-expanded={legal === 'legal'}>Informação legal</button></div></div>{legal && <div className="legal-info"><h3>{legal === 'privacidade' ? 'Privacidade neste site' : legal === 'cookies' ? 'Cookies neste site' : 'Informação legal'}</h3><p>{legal === 'privacidade' ? `Ao contactar a Premium Ride por telefone, WhatsApp ou e-mail, os dados que partilhar são utilizados apenas para responder ao seu pedido. A opção de aluguer encaminha para um formulário externo gerido pela WeGest, sujeito à respetiva política de privacidade. Não envie documentos pessoais antes de receber indicação da entidade responsável. Pode pedir esclarecimentos através de ${commercialEmail}.` : legal === 'cookies' ? 'Esta versão do site não utiliza cookies de publicidade ou analítica nem cria perfis de utilizador.' : `Premium Cars, Lda. · NIF 000 000 000 · ${demoAddress}. Atendimento 24/7. Dados societários e morada fictícios, utilizados apenas nesta demonstração.`}</p><button className="text-link" onClick={() => setLegal(null)}>Fechar</button></div>}</Container></footer>
      </>,
    ]}/>
  </>;
}
